// client/src/components/CreatePartyLine.vue
<template>
  <div>
    <input type="text" v-model="partyLineName" placeholder="Enter name" class="input input-bordered w-full max-w-xs"/>
    <button class="btn btn-outline btn-success" @click="createPartyLine">Create Party Line</button>
    <p v-if="status">{{ status }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { usePartyLineStore } from '../stores/partyLine';

const partyLineName = ref('');
const status = ref('');
const partyLineStore = usePartyLineStore();

const createPartyLine = async () => {
  if (partyLineName.value.trim()) {
    status.value = ''; // Clear previous status

    partyLineStore.createPartyLine(partyLineName.value).then((data: any) => {
      status.value = data.status;
    });

    partyLineName.value = ''; // Clear the input field

    setTimeout(() => {
      status.value = '';
    }, 5000);
  }
};
</script>

<style scoped>
input {
  padding: 8px;
  margin-right: 10px;
}

button {
  padding: 8px;
}
</style>

// client-react/src/components/CreatePartyLine.jsx
import { useState } from "react";
import { createPartyLine } from "../services/partyLineService.js";

const CreatePartyLine = () => {

  const [partyLineName, setPartyLineName] = useState('');
  const [status, setStatus] = useState('');

  const createNewPartyLine = async () => {
    if(partyLineName.trim()) {
      setStatus(''); // Clear previous status

      createPartyLine(partyLineName).then((response) => {
        setStatus(response.status)
      })

      setPartyLineName(''); // Clear input

      setTimeout(() => {
        setStatus('');
      }, 5000);
    }
  }

  return (
    <div>
      <input type="text" value={partyLineName} onChange={e => {setPartyLineName(e.target.value)}} placeholder="Enter name"
             className="input input-bordered w-full max-w-xs"/>
      <button className="btn btn-outline btn-success" onClick={createNewPartyLine}>Create Party Line</button>
      {status ? <p>{status}</p> : null}
    </div>
  )
}

export default CreatePartyLine;
