// client/src/components/JoinPartyLine.vue
<template>
  <div class="w-screen text-center">
    <input type="text" v-model="partyLineModel" placeholder="Enter Party Line"
           class="input input-bordered w-full max-w-xs"/>
    <button class="btn btn-outline btn-success" @click="joinPartyLine">Join Party Line</button>
    <br/>
    <p v-if="status"><small>{{ status }}</small></p>
    <p v-if="partyLineDeletedFlag"><small>{{ error }}</small></p>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { usePartyLineStore } from '../stores/partyLine';
import { storeToRefs } from "pinia";
import { useGetServer } from "@/composables/useGetServer.ts";

const partyLineName = ref('');
const status = ref('');
const error = ref('');
const partyLineStore = usePartyLineStore();

const { partyLine, partyLineDeletedFlag, eventSource } = storeToRefs(partyLineStore);

watch(eventSource, () => {
  if (!eventSource.value?.readyState) {
    status.value = 'Not connected to any Party Lines...';
  }
}, { immediate: true });

watch(partyLineDeletedFlag, () => {
  error.value = 'Party Line has been deleted by the admin';
}, { immediate: true });

const partyLineModel = computed({
  get: () => partyLineName.value ? partyLineName.value : partyLine.value,
  set: (value: string) => {
    partyLineName.value = value;
  }
});

const joinPartyLine = async () => {
  if (partyLineName.value.trim()) {
    partyLineDeletedFlag.value = false;
    console.log(`Attempting to join party line: ${partyLineName.value}`);
    status.value = 'Connecting...';

    // Ensure we disconnect from the current line if connected
    if (partyLine) {
      await partyLineStore.disconnectCurrentPartyLine();
    }

    fetch(`${useGetServer()}/joinPartyLine?partyLine=${encodeURIComponent(partyLineName.value)}`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    })
        .then(response => response.json().then(result => {
          status.value = result.status + ' (' + response.status + ' ' + response.statusText + ')';
          if (response.ok) {
            partyLine.value = partyLineName.value;
            partyLineStore.connectEventSource(partyLineName.value).then(() => {
              status.value = 'Connected to Party Line';

              setTimeout(() => {
                status.value = '';
              }, 3000);
            });
          } else {
            console.error('Failed to join party line with error:', response.status + ' ' + response.statusText);
          }
        }))
        .catch(error => {
          console.error('Failed to join party line with error:', error);
          status.value = error.message || 'An error occurred';
        });
  }
};
</script>

<style scoped>
input {
  padding: 8px;
  margin-right: 10px;
}

button {
  padding: 8px;
}
</style>

// client-react/src/components/JoinPartyLine.jsx
import usePartyLine from "../store/store.js";
import { useEffect, useState } from "react";
import { getServer } from "../helpers/getServer.js";
import { connectEventSource, disconnectCurrentPartyLine } from "../services/partyLineSocketService.js";

const JoinPartyLine = () => {
  const partyLine = usePartyLine((state) => state.partyLine);
  const partyLineDeleteFlag = usePartyLine((state) => state.partyLineDeletedFlag);
  const eventSource = usePartyLine((state) => state.eventSource);

  const [status, setStatus] = useState('');
  const [error, setError] = useState('');
  const [partyLineName, setPartyLineName] = useState('');

  useEffect(() => {
    if (!eventSource?.readyState) {
      setStatus('Not connected to any Party Lines...');
    }
  }, [eventSource]);

  useEffect(() => {
    if (!eventSource?.readyState) {
      setError('Party Line has been deleted by the admin!');
    }
  }, [eventSource?.readyState]);

  useEffect(() => {
    setPartyLineName(partyLineName ? partyLineName : partyLine);
  }, [partyLine])

  const joinPartyLine = async () => {
    if (partyLineName.trim()) {
      usePartyLine.setState({ partyLineDeletedFlag: false });
      console.log(`Attempting to join party line: ${partyLineName}`);
      setStatus('Connecting...');

      // Ensure we disconnect from the current line if connected
      if (partyLine) {
        await disconnectCurrentPartyLine();
      }

      fetch(`${getServer()}/joinPartyLine?partyLine=${encodeURIComponent(partyLineName)}`, {
        method: 'GET', headers: {
          'Content-Type': 'application/json',
        },
      })
        .then(response => response.json().then(result => {
          setStatus(result.status + ' (' + response.status + ' ' + response.statusText + ')');
          if (response.ok) {
            usePartyLine.setState({ partyLine: partyLineName });
            connectEventSource(partyLineName).then(() => {
              setStatus('Connected to Party Line');

              setTimeout(() => {
                setStatus('');
              }, 3000);
            });
          } else {
            console.error('Failed to join party line with error:', response.status + ' ' + response.statusText);
          }
        }))
        .catch(error => {
          console.error('Failed to join party line with error:', error);
          setStatus(error.message || 'An error occurred');
        });
    }
  }

  return (<div className="w-screen text-center">
      <input type="text" onInput={e => setPartyLineName(e.target.value)} value={partyLineName}
             placeholder="Enter Party Line"
             className="input input-bordered w-full max-w-xs"/>
      <button className="btn btn-outline btn-success" onClick={joinPartyLine}>Join Party Line</button>
      <br/>
      {status ? <p><small>{status}</small></p> : null}
      {partyLineDeleteFlag ? <p><small>{error}</small></p> : null}
    </div>)
}

export default JoinPartyLine;
